use crate::idt::InterruptDescriptorTable;
use crate::io::{inb, outb};

/// A temporary atomic-like raw tracker for the current cursor column position.
/// This prevents characters from stacking on top of each other.
static mut TEXT_CURSOR_POS: isize = 0;

/// Represents the fundamental execution context pushed onto the stack
/// by x86-64 hardware before routing execution to an exception handler.
#[repr(C)]
pub struct InterruptStackFrame {
    /// The memory instruction pointer pointing to the instruction that caused the exception.
    pub instruction_pointer: u64,
    /// The code segment selector index register.
    pub code_segment: u64,
    /// The EFLAGS register containing processor status and control flags.
    pub cpu_flags: u64,
    /// The active stack pointer register at the time the exception was caught.
    pub stack_pointer: u64,
    /// The stack segment selector index register.
    pub stack_segment: u64,
}

/// The global instance of our kernel's interrupt vector layout.
///
/// Kept statically in memory for the duration of execution runtime. Marked as
/// mutable to allow early-boot runtime registration of handler functions.
static mut IDT: InterruptDescriptorTable = InterruptDescriptorTable::new();

/// Remaps the legacy Programmable Interrupt Controllers (PIC) so hardware interrupts
/// do not overlap with native CPU exceptions (0x00 - 0x1F).
unsafe fn remap_pic() {
    // ICW1: Start initialization sequence for both PICs
    outb(0x20, 0x11);
    outb(0xA0, 0x11);

    // ICW2: Set vector offsets (Master PIC = 0x20, Slave PIC = 0x28)
    outb(0x21, 0x20);
    outb(0xA1, 0x28);

    // ICW3: Tell Master PIC that there is a slave PIC at IRQ2 (0x04)
    outb(0x21, 0x04);
    // Tell Slave PIC its cascade identity (0x02)
    outb(0xA1, 0x02);

    // ICW4: Set 8086/88 mode
    outb(0x21, 0x01);
    outb(0xA1, 0x01);

    // Clear masks to enable hardware interrupts
    outb(0x21, 0x00);
    outb(0xA1, 0x00);
}

/// Initializes the IDT matrix, registers exception handlers, remaps the PIC, and loads the table register.
///
/// This safely structures the vector mappings before communicating the table address
/// directly to the CPU control registers.
#[allow(static_mut_refs)]
pub fn init_idt() {
    unsafe {
        // Breakpoint Handler (Vector 3)
        let bp_address = breakpoint_handler as *const () as u64;
        IDT.edit_entry(3).set_handler(bp_address);

        // Hardware Timer Handler (Vector 32 / 0x20)
        // Dynamically catches early hardware clock updates to block system reboots.
        let timer_address = timer_handler as *const () as u64;
        IDT.edit_entry(0x20).set_handler(timer_address);

        // Keyboard Handler (Vector 33 / 0x21)
        let kb_address = keyboard_handler as *const () as u64;
        IDT.edit_entry(0x21).set_handler(kb_address);

        // Instruct the CPU to activate this table
        IDT.load();
        remap_pic();
        enable_cursor();

        // Configure hardware routing
        remap_pic();
    }
}

/// The specific handler invoked automatically by vector 3 breakpoint traps.
///
/// Uses the unstable "x86-interrupt" ABI calling convention to safely clean
/// up the custom hardware stack frame upon execution completion.
pub extern "x86-interrupt" fn breakpoint_handler(_frame: InterruptStackFrame) {
    loop {}
}

/// The Hardware Timer Interrupt Service Routine (IRQ 0 / Vector 0x20).
///
/// Catches the system clock pulses generated by the Programmable Interrupt Timer (PIT).
/// Safely broadcasts an End-of-Interrupt (EOI) command to prevent hardware deadlock.
pub extern "x86-interrupt" fn timer_handler(_frame: InterruptStackFrame) {
    unsafe {
        // Inform the PIC that the interrupt traffic clear is complete
        outb(0x20, 0x20);
    }
}

/// The Keyboard Interrupt Service Routine (IRQ 1 / Vector 0x21).
pub extern "x86-interrupt" fn keyboard_handler(_frame: InterruptStackFrame) {
    unsafe {
        let scancode = inb(0x60);

        // A basic look-up array where index = scancode, value = ASCII character
        // This covers a few basic keys on a standard US keyboard map
        const SCANCODE_TO_ASCII: [char; 58] = [
            '\0', '\x1B', '1', '2', '3', '4', '5', '6', '7', '8', '9', '0', '-', '=', '\x08', '\t',
            'q', 'w', 'e', 'r', 't', 'y', 'u', 'i', 'o', 'p', '[', ']', '\n', '\0', 'a', 's', 'd',
            'f', 'g', 'h', 'j', 'k', 'l', ';', '\'', '`', '\0', '\\', 'z', 'x', 'c', 'v', 'b', 'n',
            'm', ',', '.', '/', '\0', '*', '\0', ' ',
        ];

        // Ensure the keypress is a "make" code (pressed down) and within our array bounds
        if scancode & 0x80 == 0 && (scancode as usize) < SCANCODE_TO_ASCII.len() {
            let character = SCANCODE_TO_ASCII[scancode as usize];
            let vga_buffer = 0xB8000 as *mut u8;

            if character == '\x08' {
                // Backspace logic: Move back 1 character cell (2 bytes) if we aren't at the start
                if TEXT_CURSOR_POS > 0 {
                    TEXT_CURSOR_POS -= 2;
                    // Wipe the character on screen by replacing it with a blank space
                    *vga_buffer.offset(TEXT_CURSOR_POS) = b' ';
                    *vga_buffer.offset(TEXT_CURSOR_POS + 1) = 0x07; // Default dim gray attribute
                }
            } else if character != '\0' {
                // Regular character logic: Write character and advance cursor
                *vga_buffer.offset(TEXT_CURSOR_POS) = character as u8;
                *vga_buffer.offset(TEXT_CURSOR_POS + 1) = 0x0A; // Green text attribute

                TEXT_CURSOR_POS += 2;

                // Screen boundary guard: Wrap back to top left if the screen fills up
                // 80 columns * 25 rows * 2 bytes/cell = 4000 bytes
                if TEXT_CURSOR_POS >= 4000 {
                    TEXT_CURSOR_POS = 0;
                }
            }
        }

        sync_hardware_cursor();

        // Inform the PIC that the interrupt traffic clear is complete
        outb(0x20, 0x20);
    }
}

/// Enables the VGA cursor
unsafe fn enable_cursor() {
    outb(0x3D4, 0x0A);
    let val = inb(0x3D5);
    outb(0x3D5, (val & 0xC0) | 14);

    outb(0x3D4, 0x0B);
    let val = inb(0x3D5);
    outb(0x3D5, (val & 0xE0) | 15);
}

/// Syncs the VGA cursor
unsafe fn sync_hardware_cursor() {
    let offset = (TEXT_CURSOR_POS / 2) as u16;
    outb(0x3D4, 0x0F);
    outb(0x3D5, (offset & 0xFF) as u8);
    outb(0x3D4, 0x0E);
    outb(0x3D5, ((offset >> 8) & 0xFF) as u8);
}
